### ISSUE TITLE
Upload failed due to wrong `content_type`

### ISSUE THREAD

**Issue by HeinrichAD** [megasanjay/upload-to-zenodo#54]
While using this action, I always result in the error `Invalid 'Content-Type' header`. It seems that the content type `application/zip` is not supported anymore and that all uploads expect the content type `application/octet-stream`.

Log:

```txt
Preparing CiteTest-0.0.14.zip upload...
File name: CiteTest-0.0.14.zip
File path: /home/runner/work/CiteTest/CiteTest/release-assets/CiteTest-0.0.14.zip
Uploading file CiteTest-0.0.14.zip to https://zenodo.org/api/files/XX9b7bc1-d21c-4a00-8829-069984b5e0XX/CiteTest-0.0.14.zip
Error: Error with zenodo upload: Invalid 'Content-Type' header. Expected one of: application/octet-stream
Error: Could not upload file to Zenodo.
Error: Could not upload file to Zenodo. Error
Deleting Zenodo deposition 138700XX
```

I saw the code comments here:

https://github.com/megasanjay/upload-to-zenodo/blob/6625224071075967e5b4dcdb1289e350b4611d7f/src/zenodo.js#L141-L149

If I check the referred repository, they changed these lines of code 9 month ago and now always use  `application/octet-stream`. The changes can be found in commit [8e38853](https://github.com/zenodraft/zenodraft/commit/8e388531c84d711855c6d1e5b2a7fd5becbb5f08#diff-69c4b1291f1d2f405bf075d9f39fa51b7dd15389a6d59b0fb2c3fe99887027c0L24). Also look into the [current code snippet](https://github.com/zenodraft/zenodraft/blame/ddb4b0159f62ffd2b95e99fe40ba4f4024d48e5b/src/lib/file/add.ts#L15-L22).

**Comment by codingpaula** [comment]
@megasanjay could you please take a look at the PR that would solve this issue #55?

**Comment by codingpaula** [comment]
@megasanjay we tested the action now in [our repo](https://github.com/zauberzeug/nicegui/actions/runs/12411497770/job/34649322603) using the main branch, but still get the same error. I still had some to dos left on my PR (#55) including the build step that yielded some weird results for me.
Can you take a look what might be the problem here?
